spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_rest_app_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
